name: Python Package using Conda

on: [push]
#A workflow job running sequentially
jobs:
  build:
    #runs-on: defines The workflow runner
    runs-on: self-hosted 
    #steps: defines a series of tasks executed by the Job
    steps:
    - uses: actions/checkout@v2
    - run: |   # To fetch all history for all tags and branches
        git fetch --prune --unshallow  

    #Task for setting up Python 3.8 using actions/setup-python@v2 Github action
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10 # Modify python version HERE

    #Task for installing dependencies, multi-line command
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
